package com.yscredit.pgp.mybatis.model;

import java.util.Date;

public class DataInvalidStatistic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.DEPT_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.INVALID_TYPE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer invalidType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.INVALID_RATE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer invalidRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.INVALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer invalidNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.TOTAL_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer totalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_invalid_statistic.CREATE_DATE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.ID
     *
     * @return the value of data_invalid_statistic.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.ID
     *
     * @param id the value for data_invalid_statistic.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.DEPT_CODE
     *
     * @return the value of data_invalid_statistic.DEPT_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.DEPT_CODE
     *
     * @param deptCode the value for data_invalid_statistic.DEPT_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setDeptCode(Integer deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.TABLE_ID
     *
     * @return the value of data_invalid_statistic.TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.TABLE_ID
     *
     * @param tableId the value for data_invalid_statistic.TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.INVALID_TYPE
     *
     * @return the value of data_invalid_statistic.INVALID_TYPE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getInvalidType() {
        return invalidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.INVALID_TYPE
     *
     * @param invalidType the value for data_invalid_statistic.INVALID_TYPE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidType(Integer invalidType) {
        this.invalidType = invalidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.INVALID_RATE
     *
     * @return the value of data_invalid_statistic.INVALID_RATE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getInvalidRate() {
        return invalidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.INVALID_RATE
     *
     * @param invalidRate the value for data_invalid_statistic.INVALID_RATE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidRate(Integer invalidRate) {
        this.invalidRate = invalidRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.INVALID_NUMBER
     *
     * @return the value of data_invalid_statistic.INVALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getInvalidNumber() {
        return invalidNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.INVALID_NUMBER
     *
     * @param invalidNumber the value for data_invalid_statistic.INVALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidNumber(Integer invalidNumber) {
        this.invalidNumber = invalidNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.TOTAL_NUMBER
     *
     * @return the value of data_invalid_statistic.TOTAL_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getTotalNumber() {
        return totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.TOTAL_NUMBER
     *
     * @param totalNumber the value for data_invalid_statistic.TOTAL_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setTotalNumber(Integer totalNumber) {
        this.totalNumber = totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_invalid_statistic.CREATE_DATE
     *
     * @return the value of data_invalid_statistic.CREATE_DATE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_invalid_statistic.CREATE_DATE
     *
     * @param createDate the value for data_invalid_statistic.CREATE_DATE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}