package com.yscredit.pgp.mybatis.model;

import java.io.Serializable;

public class DirectInfo implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1816739283485476721L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * direct_info.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * direct_info.DATA_INFO_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String dataInfoCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * direct_info.DEPT_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer deptCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * direct_info.DEPT_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column direct_info.ID
     *
     * @return the value of direct_info.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column direct_info.ID
     *
     * @param id the value for direct_info.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column direct_info.DATA_INFO_CODE
     *
     * @return the value of direct_info.DATA_INFO_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getDataInfoCode() {
        return dataInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column direct_info.DATA_INFO_CODE
     *
     * @param dataInfoCode the value for direct_info.DATA_INFO_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setDataInfoCode(String dataInfoCode) {
        this.dataInfoCode = dataInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column direct_info.DEPT_CODE
     *
     * @return the value of direct_info.DEPT_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column direct_info.DEPT_CODE
     *
     * @param deptCode the value for direct_info.DEPT_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setDeptCode(Integer deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column direct_info.DEPT_NAME
     *
     * @return the value of direct_info.DEPT_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column direct_info.DEPT_NAME
     *
     * @param deptName the value for direct_info.DEPT_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}
