package com.yscredit.pgp.mybatis.model;

public class InvalidReasonDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invalid_reason_dict.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invalid_reason_dict.INVALID_REASON_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String invalidReasonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invalid_reason_dict.INVALID_TYPE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer invalidType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invalid_reason_dict.ID
     *
     * @return the value of invalid_reason_dict.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invalid_reason_dict.ID
     *
     * @param id the value for invalid_reason_dict.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invalid_reason_dict.INVALID_REASON_NAME
     *
     * @return the value of invalid_reason_dict.INVALID_REASON_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getInvalidReasonName() {
        return invalidReasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invalid_reason_dict.INVALID_REASON_NAME
     *
     * @param invalidReasonName the value for invalid_reason_dict.INVALID_REASON_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidReasonName(String invalidReasonName) {
        this.invalidReasonName = invalidReasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invalid_reason_dict.INVALID_TYPE
     *
     * @return the value of invalid_reason_dict.INVALID_TYPE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getInvalidType() {
        return invalidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invalid_reason_dict.INVALID_TYPE
     *
     * @param invalidType the value for invalid_reason_dict.INVALID_TYPE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidType(Integer invalidType) {
        this.invalidType = invalidType;
    }
}