package com.yscredit.pgp.mybatis.model;

import java.util.Date;

public class StatisticInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_info.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_info.TASK_INFO_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer taskInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_info.TOTAL_DATA_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer totalDataNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_info.VALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer validNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_info.INVALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer invalidNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_info.DONE_TIME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Date doneTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistic_info.START_TIME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_info.ID
     *
     * @return the value of statistic_info.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_info.ID
     *
     * @param id the value for statistic_info.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_info.TASK_INFO_ID
     *
     * @return the value of statistic_info.TASK_INFO_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getTaskInfoId() {
        return taskInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_info.TASK_INFO_ID
     *
     * @param taskInfoId the value for statistic_info.TASK_INFO_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setTaskInfoId(Integer taskInfoId) {
        this.taskInfoId = taskInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_info.TOTAL_DATA_NUMBER
     *
     * @return the value of statistic_info.TOTAL_DATA_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getTotalDataNumber() {
        return totalDataNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_info.TOTAL_DATA_NUMBER
     *
     * @param totalDataNumber the value for statistic_info.TOTAL_DATA_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setTotalDataNumber(Integer totalDataNumber) {
        this.totalDataNumber = totalDataNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_info.VALID_NUMBER
     *
     * @return the value of statistic_info.VALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getValidNumber() {
        return validNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_info.VALID_NUMBER
     *
     * @param validNumber the value for statistic_info.VALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setValidNumber(Integer validNumber) {
        this.validNumber = validNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_info.INVALID_NUMBER
     *
     * @return the value of statistic_info.INVALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getInvalidNumber() {
        return invalidNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_info.INVALID_NUMBER
     *
     * @param invalidNumber the value for statistic_info.INVALID_NUMBER
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidNumber(Integer invalidNumber) {
        this.invalidNumber = invalidNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_info.DONE_TIME
     *
     * @return the value of statistic_info.DONE_TIME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Date getDoneTime() {
        return doneTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_info.DONE_TIME
     *
     * @param doneTime the value for statistic_info.DONE_TIME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setDoneTime(Date doneTime) {
        this.doneTime = doneTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistic_info.START_TIME
     *
     * @return the value of statistic_info.START_TIME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistic_info.START_TIME
     *
     * @param startTime the value for statistic_info.START_TIME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}