package com.yscredit.pgp.mybatis.model;

public class TableDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dict.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dict.DATA_INFO_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String dataInfoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dict.TABLE_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dict.DATABASE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String database;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dict.URL
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dict.ID
     *
     * @return the value of table_dict.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dict.ID
     *
     * @param id the value for table_dict.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dict.DATA_INFO_CODE
     *
     * @return the value of table_dict.DATA_INFO_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getDataInfoCode() {
        return dataInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dict.DATA_INFO_CODE
     *
     * @param dataInfoCode the value for table_dict.DATA_INFO_CODE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setDataInfoCode(String dataInfoCode) {
        this.dataInfoCode = dataInfoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dict.TABLE_NAME
     *
     * @return the value of table_dict.TABLE_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dict.TABLE_NAME
     *
     * @param tableName the value for table_dict.TABLE_NAME
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dict.DATABASE
     *
     * @return the value of table_dict.DATABASE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getDatabase() {
        return database;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dict.DATABASE
     *
     * @param database the value for table_dict.DATABASE
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setDatabase(String database) {
        this.database = database;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dict.URL
     *
     * @return the value of table_dict.URL
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dict.URL
     *
     * @param url the value for table_dict.URL
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }
}