package com.yscredit.pgp.mybatis.model;

public class TaskRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_relation.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_relation.TASK_INFO_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer taskInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_relation.COLLECTION_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer collectionTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_relation.VALID_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer validTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_relation.INVALID_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private Integer invalidTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_relation.INVALID_DETAIL_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    private String invalidDetailTableId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_relation.ID
     *
     * @return the value of task_relation.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_relation.ID
     *
     * @param id the value for task_relation.ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_relation.TASK_INFO_ID
     *
     * @return the value of task_relation.TASK_INFO_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getTaskInfoId() {
        return taskInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_relation.TASK_INFO_ID
     *
     * @param taskInfoId the value for task_relation.TASK_INFO_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setTaskInfoId(Integer taskInfoId) {
        this.taskInfoId = taskInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_relation.COLLECTION_TABLE_ID
     *
     * @return the value of task_relation.COLLECTION_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getCollectionTableId() {
        return collectionTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_relation.COLLECTION_TABLE_ID
     *
     * @param collectionTableId the value for task_relation.COLLECTION_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setCollectionTableId(Integer collectionTableId) {
        this.collectionTableId = collectionTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_relation.VALID_TABLE_ID
     *
     * @return the value of task_relation.VALID_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getValidTableId() {
        return validTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_relation.VALID_TABLE_ID
     *
     * @param validTableId the value for task_relation.VALID_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setValidTableId(Integer validTableId) {
        this.validTableId = validTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_relation.INVALID_TABLE_ID
     *
     * @return the value of task_relation.INVALID_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public Integer getInvalidTableId() {
        return invalidTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_relation.INVALID_TABLE_ID
     *
     * @param invalidTableId the value for task_relation.INVALID_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidTableId(Integer invalidTableId) {
        this.invalidTableId = invalidTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_relation.INVALID_DETAIL_TABLE_ID
     *
     * @return the value of task_relation.INVALID_DETAIL_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public String getInvalidDetailTableId() {
        return invalidDetailTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_relation.INVALID_DETAIL_TABLE_ID
     *
     * @param invalidDetailTableId the value for task_relation.INVALID_DETAIL_TABLE_ID
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    public void setInvalidDetailTableId(String invalidDetailTableId) {
        this.invalidDetailTableId = invalidDetailTableId;
    }
}