package com.yscredit.pgp.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.yscredit.pgp.mybatis.model.DataInvalidStatistic;

@Repository
public interface DataInvalidStatisticMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * data_invalid_statistic
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * data_invalid_statistic
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(DataInvalidStatistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * data_invalid_statistic
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(DataInvalidStatistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * data_invalid_statistic
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    DataInvalidStatistic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * data_invalid_statistic
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(DataInvalidStatistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * data_invalid_statistic
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(DataInvalidStatistic record);

    List<DataInvalidStatistic> listTopInvalidByDeptCode(@Param("deptCode") Integer deptCode,
            @Param("limit") Integer limit);
}
