package com.yscredit.pgp.mybatis.dao;

import com.yscredit.pgp.mybatis.model.DataGlobalQualityDetail;
import com.yscredit.pgp.mybatis.model.DataQualityDetail;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


import java.util.List;
import java.util.Map;

@Repository
public interface DataQualityDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_quality_detail
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_quality_detail
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(DataQualityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_quality_detail
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(DataQualityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_quality_detail
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    DataQualityDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_quality_detail
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(DataQualityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_quality_detail
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(DataQualityDetail record);



    /**
     * 查询质量最好的部门和最差的部门
     * @param condition 查询条件
     * @param limit 查询几个部门
     * @return 部门code和部门质量的Bean
     */
    List<DataGlobalQualityDetail> ListDeptOfBestAndLast(@Param("condition") String condition, @Param("limit")int limit);


    /**
     * 按表归集部门当日的质量统计
     * @param deptcode
     * @return 一个部门下所有表的质量统计list
     */
    List<DataQualityDetail> ListDeptQuality(int deptcode);


    DataQualityDetail selectAvgDeptQuality(int deptcode);
}
