package com.yscredit.pgp.mybatis.dao;

import com.yscredit.pgp.mybatis.model.DirectInfo;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository(value="directInfoMapper")
public interface DirectInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * direct_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * direct_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(DirectInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * direct_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(DirectInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * direct_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    DirectInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * direct_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(DirectInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * direct_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(DirectInfo record);

    String getDeptNameByCode(@Param("deptCode") Integer deptCode);


}
