package com.yscredit.pgp.mybatis.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.yscredit.pgp.mybatis.model.InvalidReasonDict;

@Repository
public interface InvalidReasonDictMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * invalid_reason_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * invalid_reason_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(InvalidReasonDict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * invalid_reason_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(InvalidReasonDict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * invalid_reason_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    InvalidReasonDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * invalid_reason_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(InvalidReasonDict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * invalid_reason_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(InvalidReasonDict record);


    String getInvalidTypeNameByCode(@Param("invalidType") int invalidType);
}
