package com.yscredit.pgp.mybatis.dao;

import java.util.List;
import java.util.Map;

import com.yscredit.pgp.mybatis.dao.param.StatisticInfoParam;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.yscredit.pgp.mybatis.model.StatisticInfo;

@Repository
public interface StatisticInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * statistic_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * statistic_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(StatisticInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * statistic_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(StatisticInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * statistic_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    StatisticInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * statistic_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(StatisticInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * statistic_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(StatisticInfo record);

    // 根据属性查询
    List<StatisticInfo> listByParam(StatisticInfoParam param);
}
