package com.yscredit.pgp.mybatis.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.yscredit.pgp.mybatis.model.TableDict;

@Repository
public interface TableDictMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * table_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * table_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(TableDict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * table_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(TableDict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * table_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    TableDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * table_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(TableDict record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * table_dict
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(TableDict record);


    String getTableNameByCode(@Param("tableId") int tableId);

    String getTableNameByInfoCode(@Param("dataInfoCode")String dataInfoCode);
}
