package com.yscredit.pgp.mybatis.dao;

import org.springframework.stereotype.Repository;

import com.yscredit.pgp.mybatis.model.TaskRelation;

@Repository
public interface TaskRelationMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_relation
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_relation
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(TaskRelation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_relation
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(TaskRelation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_relation
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    TaskRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_relation
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(TaskRelation record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_relation
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(TaskRelation record);
}
