package com.yscredit.pgp.mybatis.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.yscredit.pgp.mybatis.model.TaskInfo;

@Repository(value = "taskInfoMapper")
public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    TaskInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * task_info
     *
     * @mbggenerated Tue Dec 06 16:15:27 CST 2016
     */
    int updateByPrimaryKey(TaskInfo record);

    // 根据部门编码查询id
    List<Integer> selectIdByDeptCode(Integer deptCode);

    // 根据工作方式查询id
    List<Integer> selectIdByTaskType(String taskType);
}
